# Generated by Django 5.0 on 2025-05-12 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('content_created', 'Content Created'), ('content_edited', 'Content Edited'), ('content_published', 'Content Published'), ('content_archived', 'Content Archived'), ('content_commented', 'Content Commented'), ('ai_request', 'AI Request'), ('login', 'Login'), ('other', 'Other')], max_length=50, verbose_name='Activity Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activities', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20, verbose_name='Period Type')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Period Start')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Period End')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('unique_view_count', models.PositiveIntegerField(default=0, verbose_name='Unique View Count')),
                ('average_time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Average Time Spent (seconds)')),
                ('bounce_rate', models.FloatField(default=0, verbose_name='Bounce Rate')),
                ('conversion_count', models.PositiveIntegerField(default=0, verbose_name='Conversion Count')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Performance Metric',
                'verbose_name_plural': 'Content Performance Metrics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'period_type'], name='analytics_c_content_62fbab_idx')],
                'unique_together': {('content_type', 'object_id', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='Session ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, verbose_name='Referrer')),
                ('content_title', models.CharField(blank=True, max_length=255, verbose_name='Content Title')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Viewed At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='analytics_p_content_73920a_idx')],
            },
        ),
    ]
