# Generated by Django 5.2 on 2025-04-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(max_length=60, unique=False, blank=True, null=True),
        ),
    ]
